{% set name = "sigpy" %}
{% set version = "0.1.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37fdc159129b6a18b44d6bee43106561d1b031343660c4168f362a91f1b49367

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - numpy <2
    - pywavelets
    - numba
    - scipy
    - tqdm
  run:
    - python >={{ python_min }}
    - numpy <2
    - pywavelets
    - numba
    - scipy
    - tqdm

test:
  imports:
    - sigpy
    - sigpy.mri
  commands:
    - pip check
    - pytest tests --ignore=tests/learn --ignore=tests/test_version.py -v
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: http://github.com/mikgroup/sigpy
  summary: Python package for signal reconstruction.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - frankong
    - sidward 
    - gschramm
