{% set name = "sigpy" %}
{% set version = "0.1.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mikgroup/sigpy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e810d044eab57642ad48ee9ff56ddeb60544a8b17ceb242345b44c5429ef02a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
    - pywavelets
    - numba
    - scipy
    - tqdm
  run:
    - python >=3.6
    - numpy
    - pywavelets
    - numba
    - scipy
    - tqdm

test:
  imports:
    - sigpy
    - sigpy.mri
  commands:
    - pip check
    - pytest tests --ignore=tests/learn -v
  source_files:
    - tests
  requires:
    - pip
    - pytest

about:
  home: http://github.com/mikgroup/sigpy
  summary: Python package for signal reconstruction.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - frankong
    - sidward 
    - gschramm
